export default [{
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/b75b65944a9730166ea2df8446f8f6a9f67b9286.png?x=x",
  "timestamp": 1474589191,
  "display_recipient": "development help",
  "sender_id": 131,
  "sender_full_name": "Rishi Gupta",
  "sender_domain": "tabbott.net",
  "content": "<p>Is anyone else having problems with <code>zerver.tests.test_narrow.GetOldMessagesTest.test_get_old_messages_with_search_pgroonga<\/code>? For me it sometimes passes locally and sometimes doesn't, and has failed on travis both times I tried (this is for a change unrelated to that set of tests). When it fails I get <\/p>\n<div class=\"codehilite\"><pre>Running zerver.tests.test_narrow.GetOldMessagesTest.test_get_old_messages_with_search_pgroonga\nTraceback (most recent call last):\n  File &quot;\/home\/travis\/build\/rishig\/zulip\/zerver\/lib\/test_runner.py&quot;, line 129, in run_test\n    test_method()\n  File &quot;\/srv\/zulip-venv\/local\/lib\/python2.7\/site-packages\/django\/test\/utils.py&quot;, line 196, in inner\n    return test_func(*args, **kwargs)\n  File &quot;\/home\/travis\/build\/rishig\/zulip\/zerver\/tests\/test_narrow.py&quot;, line 605, in test_get_old_messages_with_search_pgroonga\n    self.assertEqual(len(result[&#39;messages&#39;]), 4)\n  File &quot;\/usr\/lib\/python2.7\/unittest\/case.py&quot;, line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File &quot;\/usr\/lib\/python2.7\/unittest\/case.py&quot;, line 508, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 1 != 4\nHTML report saved to var\/coverage\nFAILED!\n<\/pre><\/div>",
  "gravatar_hash": "1cc5f08eb7d952a08d0553b788516000",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "rishig@zulipchat.com",
  "subject_links": [],
  "subject": "pgroonga heisentest",
  "type": "stream",
  "id": 28174,
  "sender_short_name": "rishig"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/b60683e6dacd4556ae15430a7c9b6f13?d=identicon",
  "timestamp": 1474589251,
  "display_recipient": "development help",
  "sender_id": 58,
  "sender_full_name": "Steve Howell",
  "sender_domain": "tabbott.net",
  "content": "<p>rebase to the latest master...this has been fixed<\/p>",
  "gravatar_hash": "b60683e6dacd4556ae15430a7c9b6f13",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "showell30@yahoo.com",
  "subject_links": [],
  "subject": "pgroonga heisentest",
  "type": "stream",
  "id": 28175,
  "sender_short_name": "showell30"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/b75b65944a9730166ea2df8446f8f6a9f67b9286.png?x=x",
  "timestamp": 1474589268,
  "display_recipient": "development help",
  "sender_id": 131,
  "sender_full_name": "Rishi Gupta",
  "sender_domain": "tabbott.net",
  "content": "<p>cool, thanks!<\/p>",
  "gravatar_hash": "1cc5f08eb7d952a08d0553b788516000",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "rishig@zulipchat.com",
  "subject_links": [],
  "subject": "pgroonga heisentest",
  "type": "stream",
  "id": 28176,
  "sender_short_name": "rishig"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/b60683e6dacd4556ae15430a7c9b6f13?d=identicon",
  "timestamp": 1474589296,
  "display_recipient": "development help",
  "sender_id": 58,
  "sender_full_name": "Steve Howell",
  "sender_domain": "tabbott.net",
  "content": "<p>:)<\/p>",
  "gravatar_hash": "b60683e6dacd4556ae15430a7c9b6f13",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "showell30@yahoo.com",
  "subject_links": [],
  "subject": "pgroonga heisentest",
  "type": "stream",
  "id": 28177,
  "sender_short_name": "showell30"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474620116,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p>Hi! My name is Reyha Verma. I made changes to search.js while working on issue <a href=\"https:\/\/github.com\/zulip\/zulip\/pull\/1743\" target=\"_blank\" title=\"https:\/\/github.com\/zulip\/zulip\/pull\/1743\">#1743<\/a> (<a href=\"https:\/\/github.com\/zulip\/zulip\/issues\/1743\" target=\"_blank\" title=\"https:\/\/github.com\/zulip\/zulip\/issues\/1743\">https:\/\/github.com\/zulip\/zulip\/issues\/1743<\/a>) . I opened a pull request (<a href=\"https:\/\/github.com\/zulip\/zulip\/pull\/1842\" target=\"_blank\" title=\"https:\/\/github.com\/zulip\/zulip\/pull\/1842\">https:\/\/github.com\/zulip\/zulip\/pull\/1842<\/a>) for this but I get Travis CI build failure. Any help on how to proceed would be great!<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28226,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/bbd8f8073ada6bc54ed57f7bd822e1d3?d=identicon",
  "timestamp": 1474621265,
  "display_recipient": "development help",
  "sender_id": 21,
  "sender_full_name": "Eklavya Sharma",
  "sender_domain": "tabbott.net",
  "content": "<p>Did you test your changes locally by running <code>tools\/test-js-with-casper<\/code>? What output did you get?<\/p>\n<p>Did you look at the Travis CI frontend build output? If you didn't, you can do that by clicking on the red build failure cross icon on the pull request page on github.<\/p>",
  "gravatar_hash": "bbd8f8073ada6bc54ed57f7bd822e1d3",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "ekurgn@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28227,
  "sender_short_name": "ekurgn"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474621407,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I think you must validate if the search string is a valid URL or not and make sure that you add \" to the beginning and end of it only if they do not exist.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28228,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474621452,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>You may use the function on this page to validate a URL in javascript <a href=\"http:\/\/stackoverflow.com\/questions\/5717093\/check-if-a-javascript-string-is-a-url\" target=\"_blank\" title=\"http:\/\/stackoverflow.com\/questions\/5717093\/check-if-a-javascript-string-is-a-url\">validate urls<\/a><\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28229,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474636757,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>The function in this page did not work try this one it worked for me.<\/p>\n<div class=\"codehilite\"><pre>     function ValidURL(str) {\n      var pattern = \/(ftp|http|https):\\\/\\\/(\\w+:{0,1}\\w*@)?(\\S+)(:[0-9]+)?(\\\/|\\\/([\\w#!:.?+=&amp;%@!\\-\\\/]))?\/;\n        if(!pattern.test(str)) {\n          return false;\n        } else {\n          return true;\n        }\n    }\n<\/pre><\/div>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28234,
  "sender_short_name": "mohsen47"
}, {
  "edit_history": [{
    "prev_content": "Yes, hanks a lot! This code works fine for a URL but I think the problem is with the symbol colon (:) in the link. If I try to search any item that contains a colon other than a URL, it again returns to the homepage instead of going to the 'no results found' page. ",
    "timestamp": 1474642029,
    "prev_rendered_content": "<p>Yes, hanks a lot! This code works fine for a URL but I think the problem is with the symbol colon (:) in the link. If I try to search any item that contains a colon other than a URL, it again returns to the homepage instead of going to the 'no results found' page. <\/p>",
    "prev_rendered_content_version": 1
  }],
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474642017,
  "display_recipient": "development help",
  "sender_id": 311,
  "last_edit_timestamp": 1474642029,
  "subject": "Travis CI build failure",
  "sender_full_name": "Reyha Verma",
  "content": "<p>Yes, Thanks a lot! This code works fine for a URL but I think the problem is with the symbol colon (:) in the link. If I try to search any item that contains a colon other than a URL, it again returns to the homepage instead of going to the 'no results found' page.<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "sender_domain": "tabbott.net",
  "type": "stream",
  "id": 28290,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474642193,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p><span class=\"user-mention\" data-user-email=\"mohsen47@hotmail.co.uk\">@Mohsen Ibrahim<\/span>  Yes, Thanks a lot! This code works fine for a URL but I think the problem is with the symbol colon (:) in the link. If I try to search any item that contains a colon other than a URL, it again returns to the homepage instead of going to the 'no results found' page.<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28291,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474644845,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>Then we should add double quotes to all search strings which contain a colon?<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28295,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474645310,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p>Yes, I tried to do it this way but it fails again in Travis CI tests<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": ["read"],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28310,
  "sender_short_name": "reyhaverma"
}, {
  "edit_history": [{
    "prev_content": "I think you should do ad @**Eklavya Sharma told you, run the tests locally and try to figure out why it is failing.",
    "timestamp": 1474645411,
    "prev_rendered_content": "<p>I think you should do ad @**Eklavya Sharma told you, run the tests locally and try to figure out why it is failing.<\/p>",
    "prev_rendered_content_version": 1
  }],
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474645396,
  "display_recipient": "development help",
  "sender_id": 248,
  "last_edit_timestamp": 1474645411,
  "subject": "Travis CI build failure",
  "sender_full_name": "Mohsen Ibrahim",
  "content": "<p>I think you should do ad @<strong>Eklavya<\/strong> Sharma told you, run the tests locally and try to figure out why it is failing.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "sender_domain": "tabbott.net",
  "type": "stream",
  "id": 28315,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474646928,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I am trying to debug the java script code but I cannot find the javaScript file <code>search.js<\/code> do you have any idea how can I find it to debug the code?<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28344,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474646964,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>All our js is under <code>static\/js<\/code><\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28345,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474646993,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>In any software project, you can find a file by filename using <code>find . | grep search.js<\/code> at the root of the repository.<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28346,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474647046,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I am using vivaldi web bowser and I cannot find the file in <code>static<\/code> even the folder <code>static\/js<\/code> cannot be found.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28347,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474647095,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p><a href=\"https:\/\/github.com\/zulip\/zulip\/tree\/master\/static\/js\" target=\"_blank\" title=\"https:\/\/github.com\/zulip\/zulip\/tree\/master\/static\/js\">https:\/\/github.com\/zulip\/zulip\/tree\/master\/static\/js<\/a> is how you can find it in the GitHub UI<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28348,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474647138,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>But, I guess I don't really understand what you're trying to do.  Can you explain in more detail?<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28349,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474647167,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I can find it in the GitHub UI but I want to add break points to it and try to step in the code to find out where the problem is, do you understand me now?<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28350,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474647412,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p>All the tests are running fine on my local machine but still shows errors while running the Travis CI tests. Here is a screenshot of my local machine <a href=\"\/user_uploads\/2\/d5\/gOiick4zSbaFclJ7HF5uV9-F\/pic.png\" target=\"_blank\" title=\"pic.png\">pic.png<\/a>  <\/p>\n<div class=\"message_inline_image\"><a href=\"\/user_uploads\/2\/d5\/gOiick4zSbaFclJ7HF5uV9-F\/pic.png\" target=\"_blank\" title=\"pic.png\"><img src=\"\/user_uploads\/2\/d5\/gOiick4zSbaFclJ7HF5uV9-F\/pic.png\"><\/a><\/div>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28352,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474647457,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p><span class=\"user-mention\" data-user-email=\"reyhaverma@gmail.com\">@Reyha Verma<\/span> there are no errors in that output<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28353,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474647502,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>There is the \"Unsafe javascript ...\" warning at the very end, but that shows up whenever the tests are run in Travis CI<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28354,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474648612,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p><span class=\"user-mention\" data-user-email=\"tabbott@gmail.com\">@Tim Abbott<\/span>  Thanks a lot! I was getting a bit confused with those results.<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28362,
  "sender_short_name": "reyhaverma"
}, {
  "edit_history": [{
    "prev_content": "I am still getting Travis CI errors (link: https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460) during a pull request although  ``.\/frontend_tests\/run-casper`` seems to run successfully on my local machine. Any help on how to debug these errors would be very helpful!",
    "timestamp": 1474664207,
    "prev_rendered_content": "<p>I am still getting Travis CI errors (link: <a href=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\" target=\"_blank\" title=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\">https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460<\/a>) during a pull request although  <code>.\/frontend_tests\/run-casper<\/code> seems to run successfully on my local machine. Any help on how to debug these errors would be very helpful!<\/p>",
    "prev_rendered_content_version": 1
  }, {
    "prev_content": "I am still getting Travis CI errors (link: https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460) during a pull request although  ``.\/frontend_tests\/run-casper`` seems to run successfully. on my local machine. Any help on how to debug these errors would be very helpful! \n\n ",
    "prev_rendered_content_version": 1,
    "prev_rendered_content": "<p>I am still getting Travis CI errors (link: <a href=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\" target=\"_blank\" title=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\">https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460<\/a>) during a pull request although  <code>.\/frontend_tests\/run-casper<\/code> seems to run successfully. on my local machine. Any help on how to debug these errors would be very helpful! <\/p>",
    "timestamp": 1474664184
  }],
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474664159,
  "display_recipient": "development help",
  "sender_id": 311,
  "last_edit_timestamp": 1474664207,
  "subject": "Travis CI build failure",
  "sender_full_name": "Reyha Verma",
  "content": "<p>I am still getting Travis CI errors (link: <a href=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\" target=\"_blank\" title=\"https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460\">https:\/\/travis-ci.org\/zulip\/zulip\/builds\/162281460<\/a>) during a pull request although  <code>.\/frontend_tests\/run-casper<\/code> seems to run successfully on my local machine. Any help on how to debug these errors would be really very great!<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "sender_domain": "tabbott.net",
  "type": "stream",
  "id": 28484,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/b60683e6dacd4556ae15430a7c9b6f13?d=identicon",
  "timestamp": 1474664397,
  "display_recipient": "development help",
  "sender_id": 58,
  "sender_full_name": "Steve Howell",
  "sender_domain": "tabbott.net",
  "content": "<p>The problem seems to be that your expected output and actual output are sorted differently, but otherwise have the same values.  Were the tests that are failing part of new code that you wrote or may have affected?  Do you know where to be looking in the code to find the failures?<\/p>",
  "gravatar_hash": "b60683e6dacd4556ae15430a7c9b6f13",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "showell30@yahoo.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28485,
  "sender_short_name": "showell30"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/b60683e6dacd4556ae15430a7c9b6f13?d=identicon",
  "timestamp": 1474664450,
  "display_recipient": "development help",
  "sender_id": 58,
  "sender_full_name": "Steve Howell",
  "sender_domain": "tabbott.net",
  "content": "<p>BTW one thing that happens sometimes for Travis tests (really, tests in general) is that you see the failure at the bottom, but there are more details if you scroll up.<\/p>",
  "gravatar_hash": "b60683e6dacd4556ae15430a7c9b6f13",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "showell30@yahoo.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28486,
  "sender_short_name": "showell30"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474665023,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p>Yes, actually I read about the assertEquals error that occurs in Travis CI tests! I am also trying to understand the workflow of the <code>.\/03-narrow.js<\/code> file as all the 4 tests that fail are located in this file!<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28489,
  "sender_short_name": "reyhaverma"
}, {
  "edit_history": [{
    "prev_content": "I guess the tests that are failing are related to the new code that I added but I am a little confused about the files being sorted differently?",
    "timestamp": 1474665345,
    "prev_rendered_content": "<p>I guess the tests that are failing are related to the new code that I added but I am a little confused about the files being sorted differently?<\/p>",
    "prev_rendered_content_version": 1
  }],
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474665325,
  "display_recipient": "development help",
  "sender_id": 311,
  "last_edit_timestamp": 1474665345,
  "subject": "Travis CI build failure",
  "sender_full_name": "Reyha Verma",
  "content": "<p>I guess the tests that are failing are related to the new code that I added but I am a little confused about the files being sorted differently.<\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "sender_domain": "tabbott.net",
  "type": "stream",
  "id": 28493,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690177,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I commented on you pull request about this.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28560,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690356,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I think I knew why you are getting Travis CI failed tests, when you double quote every search string that contains a colon we are losing a very important functionality here which is the ability to narrow to a stream and viewing private messages with someone because these functionalities use special search strings with colons inside them and here you are quoting these strings so they are used as string literals when searching. I think the problem lies somewhere else in the code.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28561,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690670,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>Hi I am trying to setup my own development environment using the docs here <a href=\"https:\/\/zulip.readthedocs.io\/en\/latest\/install-ubuntu-without-vagrant-dev.html\" target=\"_blank\" title=\"https:\/\/zulip.readthedocs.io\/en\/latest\/install-ubuntu-without-vagrant-dev.html\">https:\/\/zulip.readthedocs.io\/en\/latest\/install-ubuntu-without-vagrant-dev.html<\/a> <\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28563,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690810,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I was getting this error<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28564,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690810,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<div class=\"codehilite\"><pre>\n<\/pre><\/div>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28565,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690810,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<div class=\"codehilite\"><pre>+  virtualenv \/srv\/zulip-venv-cache\/0cb8dd21b68bbc917138352cbe14971913b6c254\/zulip-venv\nTraceback (most recent call last):\n  File &quot;.\/tools\/provision.py&quot;, line 253, in &lt;module&gt;\n    sys.exit(main())\n  File &quot;.\/tools\/provision.py&quot;, line 189, in main\n    setup_venvs.main()\n  File &quot;\/home\/mohsen\/SourceCode\/zulip\/tools\/setup\/setup_venvs.py&quot;, line 16, in main\n    setup_virtualenv(&quot;\/srv\/zulip-venv&quot;, PY2_DEV_REQS_FILE, patch_activate_script=True)\n  File &quot;\/home\/mohsen\/SourceCode\/zulip\/scripts\/lib\/setup_venv.py&quot;, line 70, in setup_virtualenv\n    do_setup_virtualenv(cached_venv_path, requirements_file, virtualenv_args or [])\n  File &quot;\/home\/mohsen\/SourceCode\/zulip\/scripts\/lib\/setup_venv.py&quot;, line 89, in do_setup_virtualenv\n    run([&quot;virtualenv&quot;] + virtualenv_args + [venv_path])\n  File &quot;\/home\/mohsen\/SourceCode\/zulip\/scripts\/lib\/zulip_tools.py&quot;, line 90, in run\n    process = subprocess.Popen(args, **kwargs)\n  File &quot;\/usr\/lib\/python2.7\/subprocess.py&quot;, line 711, in __init__\n    errread, errwrite)\n  File &quot;\/usr\/lib\/python2.7\/subprocess.py&quot;, line 1343, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or director\n<\/pre><\/div>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28566,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690823,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I solved it just by manually installing <code>virtualenv<\/code> package.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28567,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690982,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I see the package <code>python-virtualenv<\/code> in <code>VENV_DEPENDENCIES<\/code> but I cannot find the package 'virtualenv` there.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28568,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/1725b84b5fa02f001350c5d1bbe196ebc893c950.png?x=x",
  "timestamp": 1474690982,
  "display_recipient": "development help",
  "sender_id": 248,
  "sender_full_name": "Mohsen Ibrahim",
  "sender_domain": "tabbott.net",
  "content": "<p>I am running Ubuntu 16.04 maybe the name of the package changed in this version.<\/p>",
  "gravatar_hash": "fae9db9053fe08e01f5c059b20411007",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "mohsen47@hotmail.co.uk",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28569,
  "sender_short_name": "mohsen47"
}, {
  "content_type": "text\/html",
  "avatar_url": "https:\/\/secure.gravatar.com\/avatar\/5382337f779000054f03c9640f1af94d?d=identicon",
  "timestamp": 1474714506,
  "display_recipient": "development help",
  "sender_id": 311,
  "sender_full_name": "Reyha Verma",
  "sender_domain": "tabbott.net",
  "content": "<p>Yes, that is absolutely true! But the last commit that  I made auto-quotes the URL only and not all strings that contain a colon. Four tests still fail the Travis CI test. I get the output message as B C C D when it is supposed to be A B C D. It is not properly sorted like Steve Howell mentioned above. <\/p>",
  "gravatar_hash": "5382337f779000054f03c9640f1af94d",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "reyhaverma@gmail.com",
  "subject_links": [],
  "subject": "Travis CI build failure",
  "type": "stream",
  "id": 28580,
  "sender_short_name": "reyhaverma"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474737469,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>Hmm, it looks like indeed the <code>python-virtualenv<\/code> package was renamed to <code>virtualenv<\/code> (which actually just depends on <code>python3-virtualenv<\/code>)<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28585,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474737505,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>I think the current thing should work correctly on Xenial, but certainly isn't future-proof for once the <code>python-virtualenv<\/code> package stops existing entirely<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28586,
  "sender_short_name": "tabbott"
}, {
  "content_type": "text\/html",
  "avatar_url": "\/user_avatars\/925a7b8f539dea91b0a92e1e7bd91d92d1ddec0b.png?x=x",
  "timestamp": 1474737542,
  "display_recipient": "development help",
  "sender_id": 7,
  "sender_full_name": "Tim Abbott",
  "sender_domain": "tabbott.net",
  "content": "<p>We can just patch <code>setup_venv.py<\/code> to use <code>virtualenv<\/code> on newer Debian\/Ubuntu<\/p>",
  "gravatar_hash": "034862d9db3886dabca1bea87bfc3612",
  "recipient_id": 424,
  "flags": [],
  "client": "website",
  "sender_email": "tabbott@gmail.com",
  "subject_links": [],
  "subject": "missing dependecies",
  "type": "stream",
  "id": 28587,
  "sender_short_name": "tabbott"
}];
